### ISSUE TITLE
Invoice Dataset is missing

### ISSUE THREAD

**Issue by ninjakx** [bikash/DocumentUnderstanding#2]
That google drive link contains empty folder.

**Comment by bikash** [comment]
Looks like author has deleted the invoice datasets. You can use receipt datasets 
https://www.kaggle.com/jpmiller/layoutlm-starter
https://drive.google.com/drive/folders/1ShItNWXyiY1tFDM5W02bceHuJjyeeJl2
or doc bank
https://doc-analysis.github.io/docbank-page/
